
name: Deploy Monitor Script

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          mkdir -p ~/scripts
          echo "${{ github.event.head_commit.message }}" > ~/scripts/commit.txt
          cp ./monitor.sh ~/scripts/monitor.sh
          chmod +x ~/scripts/monitor.sh
          (crontab -l ; echo "*/5 * * * * ~/scripts/monitor.sh") | sort - | uniq - | crontab -
